{
 "title": "Performance",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, routeId) (rate(spring_cloud_gateway_requests_seconds_bucket[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_sum[5m])) by (routeId)\n/\n(sum(rate(spring_cloud_gateway_requests_seconds_count[5m])) by (routeId))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM heap memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 * (sum(\n  avg_over_time(jvm_memory_used_bytes{area=\"heap\"}[5m])\n) by (service)\n/\nsum(\n  avg_over_time(jvm_memory_max_bytes{area=\"heap\"}[5m])\n) by (service)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(avg_over_time(system_cpu_usage[5m])) by (service) * 100",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}