apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: authorization-server
  name: authorization-server
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: authorization-server
  type: LoadBalancer
status:
  loadBalancer: {}
