apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: authorization-server
  name: authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: authorization-server
    spec:
      containers:
      - image: localhost:5000/betting-app/authorization-server
        name: authorization-server
        resources: {}
status: {}
