apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bet-service
  name: bet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bet-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bet-service
    spec:
      containers:
      - image: localhost:5000/betting-app/bet-service
        name: bet-service
        resources: {}
status: {}
