apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: login-service
  name: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: login-service
    spec:
      containers:
      - image: localhost:5000/betting-app/login-service
        name: login-service
        resources: {}
status: {}
