apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: bet-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: 80-8080
      path: /actuator/prometheus
      interval: 15s
